export const IMAGES = {
  user: require('./image/user.png'),
  pen: require('./image/pen.png'),
  ic_down: require('./image/ic_down.png'),
  ic_share: require('./image/ic_share.png'),
  quality: require('./image/quality.png'),
  share: require('./image/share.png'),
  back: require('./image/back.png'),
  qr: require('./image/qr.png'),
  logo: require('./image/logo.png'),
  close: require('./image/close.png'),
  checked: require('./image/checked.png'),
  cancel: require('./image/cancel.png'),
  google: require('./icon/google.png'),
  apple: require('./icon/apple.png'),
  headerLogo: require('./icon/logo.png'),
  welcome: require('./image/welcome.png'),
  visibility_off: require('./image/visibility_off.png'),
  visibility: require('./image/visibility.png'),
  bg: require('./image/bg.png'),
  calnder: require('./image/calnder.png'),
  lock: require('./image/lock.png'),
  map: require('./image/map.png'),
  photo: require('./image/photo.png'),
  public: require('./image/public.png'),
  tick: require('./image/tick.png'),
  right: require('./image/right.png'),
  check1: require('./image/check1.png'),
  intro1: require('./image/info1.png'),
  intro2: require('./image/info2.png'),
  intro3: require('./image/info3.png'),
  intro4: require('./image/info4.png'),
  intro5: require('./image/info5.png'),

  //create
  trip_bg: require('./icon/create/trip_bg.png'),
  requestHost_bg: require('./icon/create/requestHost_bg.png'),
  list_bg: require('./icon/create/list_bg.png'),
  Itinerary_bg: require('./icon/create/Itinerary_bg.png'),
  experience_bg: require('./icon/create/experience_bg.png'),
  event_bg: require('./icon/create/event_bg.png'),
  canlder: require('./icon/create/canlder.png'),
  camera: require('./icon/create/camera.png'),
  bucketList_bg: require('./icon/create/bucketList_bg.png'),
    location: require('./icon/create/location.png'),

  //tab
  trips: require('./icon/tab/trips.png'),
  profile: require('./icon/tab/profile.png'),
  newList: require('./icon/tab/newList.png'),
  shape: require('./icon/tab/shape.png'),
  search: require('./icon/tab/search.png'),
};
